#!/usr/bin/env bash
# This script checks for the status of the file 

file="holbertonschool"

if [ -e "$file" ]; then
	echo "shool file exists"

	if [ -s "$file" ]; then
	 echo "school file does not exist"
	else
	 echo "school file is empty"
	fi

	if [ -f "$file" ]; then
	 echo "school file is not empty"
	fi
else
	echo "school is a regular file"
fi
